In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("C:/Users/Owner/Desktop/Scrapping Project/data.csv")

In [5]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
1,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,"Data Scientist - Statistics, Early Career",$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
3,"Medical Laboratory Scientist (MLS), ASCP, MT",$64K-$106K (Glassdoor est.),Description of role: Collect and analyze toena...,3.7,Advanced Foot and Ankle Care\n3.7,"Memphis, TN","Nashville, TN",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
4,Data Scientist,$64K-$106K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
5,Staff Data Scientist - Analytics,$64K-$106K (Glassdoor est.),Intuit is seeking a Staff Data Scientist to co...,4.4,Intuit - Data\n4.4,"San Diego, CA","Mountain View, CA",5001 to 10000 employees,1983,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),"Square, PayPal, H&R Block"
6,Sr Data Scientist,$64K-$106K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,Chemical Manufacturing,Manufacturing,$10+ billion (USD),-1
7,Associate Business Intelligence Data Scientist,$64K-$106K (Glassdoor est.),"Blending customer advisory, customer support, ...",3.1,Carousel Industries\n3.1,"Exeter, RI","Exeter, RI",1001 to 5000 employees,1992,Company - Private,IT Services,Information Technology,$500 million to $1 billion (USD),-1
8,Data Scientist / Machine Learning Expert,$64K-$106K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
9,Senior Data Scientist,$64K-$106K (Glassdoor est.),"At Recursion, nothing is more important than t...",4.7,Recursion Pharmaceuticals\n4.7,"Salt Lake City, UT","Salt Lake City, UT",51 to 200 employees,2013,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),-1
10,Data Scientist,$64K-$106K (Glassdoor est.),Job Brief\n\nThe ideal candidate will have pre...,2.9,IFG Companies\n2.9,"New York, NY","Hartford, CT",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,"Colony Specialty, Markel, RLI"
11,Data Analyst,$64K-$106K (Glassdoor est.),"Data Analyst\n\nLocation: Fort Meade, MD\n\nDe...",4.1,Favor TechConsulting\n4.1,"Fort Meade, MD","Vienna, VA",201 to 500 employees,2007,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1
12,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),Business Intelligence Analyst\nFull Time\nRemo...,3.2,Radius Global Solutions\n3.2,"Ambler, PA","Ambler, PA",1001 to 5000 employees,2013,Company - Private,Consulting,Business Services,Unknown / Non-Applicable,-1
13,VP Data Science & Analytics,$64K-$106K (Glassdoor est.),It's fun to work in a company where people tru...,3.6,Green Dot\n3.6,California,"Pasadena, CA",1001 to 5000 employees,1999,Company - Public,Financial Transaction Processing,Finance,$1 to $2 billion (USD),-1
14,Senior Data Scientist,$64K-$106K (Glassdoor est.),"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck\n3.8,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,Advertising & Marketing,Business Services,$10 to $25 million (USD),"Nielsen, Zappi, SurveyMonkey"
15,Data Scientist in Artificial Intelligence - In...,$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310507\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
16,Sensory Scientist,$64K-$106K (Glassdoor est.),A leading food production company in St. Louis...,3.8,NIC Infotek\n3.8,"Saint Louis, MO","Tampa, FL",51 to 200 employees,2004,Company - Public,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1
17,Medical Lab Scientist,$64K-$106K (Glassdoor est.),"Overview\n\n\nTower Health is a strong, region...",3.5,Tower Health\n3.5,"West Grove, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
18,Data Scientist,$64K-$106K (Glassdoor est.),Northrop Grumman Space Systems is looking for ...,3.7,Northrop Grumman\n3.7,"McLean, VA","Falls Church, VA",10000+ employees,1939,Company - Public,Aerospace & Defense,Aerospace & Defense,$10+ billion (USD),-1
19,Data Scientist-Human Resources,$64K-$106K (Glassdoor est.),"Lexington, MA, US\n\n#job-location.job-locatio...",3.8,MIT Lincoln Laboratory\n3.8,"Lexington, MA","Lexington, MA",1001 to 5000 employees,1951,Nonprofit Organization,Aerospace & Defense,Aerospace & Defense,Unknown / Non-Applicable,-1
20,Senior Healthcare Data Analyst - Contract Mode...,$64K-$106K (Glassdoor est.),"About Fallon Health\nFounded in 1977, Fallon H...",2.8,Fallon Health\n2.8,"Worcester, MA","Worcester, MA",1001 to 5000 employees,1977,Nonprofit Organization,Insurance Carriers,Insurance,$1 to $2 billion (USD),-1
21,Senior Data Scientist,$64K-$106K (Glassdoor est.),Summary\n\nWe’re looking for a senior data sci...,3.6,TRANZACT\n3.6,United States,"Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
22,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),"Who Are We?\n\nMerchantE is an innovative, tec...",3.0,MerchantE\n3.0,"Alpharetta, GA","Alpharetta, GA",201 to 500 employees,2000,Subsidiary or Business Segment,Financial Transaction Processing,Finance,$100 to $500 million (USD),-1
23,Data Scientist,$64K-$106K (Glassdoor est.),The Senior Data Scientist will build and impro...,3.6,Powertek\n3.6,"Washington, DC","Rockville, MD",51 to 200 employees,2001,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1
24,Data Scientist,$64K-$106K (Glassdoor est.),The Data Scientist supports the development of...,3.4,Plymouth Rock Assurance\n3.4,"Woodbridge, NJ","Boston, MA",1001 to 5000 employees,1982,Company - Private,Insurance Carriers,Insurance,$10 to $25 million (USD),"Arbella Insurance, Safety Insurance"
25,Sr Data Scientist,$64K-$106K (Glassdoor est.),"About Figure\n\nAt Figure, we're on a mission ...",4.5,Figure\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2018,Company - Private,Lending,Finance,Unknown / Non-Applicable,-1
26,"Data Analyst, Ethics & Compliance",$64K-$106K (Glassdoor est.),Job Description\n\n\nTitle: Data Analyst\n\n\n...,4.2,Cogent Infotech\n4.2,"Stamford, CT","Pittsburgh, PA",201 to 500 employees,2003,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1
27,Research Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
28,Data Scientist,$64K-$106K (Glassdoor est.),The world's largest and fastest-growing compan...,4.5,Demandbase\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2006,Company - Private,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),"Engagio, Bombora, Terminus"
29,"Real World Science, Data Scientist",$64K-$106K (Glassdoor est.),"Title: Real World Science, Data Scientist\nLoc...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
30,Sr Data Scientist,$81K-$131K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,Chemical Manufacturing,Manufacturing,$10+ billion (USD),-1
31,"Data Scientist - Statistics, Early Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
32,Data Scientist,$81K-$131K (Glassdoor est.),Back to search results\nPrevious job\n\nNext j...,3.9,Mars\n3.9,United States,"Mc Lean, VA",10000+ employees,1911,Company - Private,Food & Beverage Manufacturing,Manufacturing,$10+ billion (USD),-1
33,"Senior Manager, Clients Analytics (Data Science)",$81K-$131K (Glassdoor est.),The Opportunity\n\n\nCome build the data and a...,4.5,Livongo\n4.5,"Denver, CO","Mountain View, CA",501 to 1000 employees,2014,Company - Public,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
34,Data Scientist #5967,$81K-$131K (Glassdoor est.),Company Overview\n\nFanatics is the global lea...,3.4,Fanatics\n3.4,"San Mateo, CA","Jacksonville, FL",5001 to 10000 employees,1996,Company - Private,Sporting Goods Stores,Retail,$1 to $2 billion (USD),"Lids, Amazon, Under Armour"
35,Senior Analyst/Data Scientist,$81K-$131K (Glassdoor est.),At Edmunds were driven to make car buying easi...,3.5,Edmunds.com\n3.5,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,1966,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"TrueCar, Cars.com, Kelley Blue Book"
36,Data Scientist,$81K-$131K (Glassdoor est.),Job Title: Data Scientists\n\nJob Description\...,2.2,Great-Circle Technologies\n2.2,"Chantilly, VA","Chantilly, VA",1 to 50 employees,2000,Company - Private,Enterprise Software & Network Solutions,Information Technology,$1 to $5 million (USD),-1
37,Business Intelligence Analyst,$81K-$131K (Glassdoor est.),"Reporting to the Director, Marketing Analytics...",3.7,Zimmerman Advertising\n3.7,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 to 1000 employees,1984,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
38,Data Scientist,$81K-$131K (Glassdoor est.),It's fun to work in a company where people tru...,3.3,NAVEX Global\n3.3,"Lake Oswego, OR","Lake Oswego, OR",1001 to 5000 employees,2012,Company - Private,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),-1
39,Data Analyst,$81K-$131K (Glassdoor est.),File #: 2020-26-0616\nPosition: Data Analyst –...,4.4,Shared Services West\n4.4,Remote,"Burlington, Canada",51 to 200 employees,2001,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,Plexxus
40,"Data Scientist - Statistics, Mid-Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310919\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
41,"Risk and Analytics IT, Data Scientist",$81K-$131K (Glassdoor est.),OUR AGENCY\n\nMaking a Difference\n\nSWIB is a...,2.9,State of Wisconsin Investment Board\n2.9,"Madison, WI","Madison, WI",51 to 200 employees,1951,Government,Investment Banking & Asset Management,Finance,$50 to $100 million (USD),-1
42,Research Scientist,$81K-$131K (Glassdoor est.),"Job Summary:\n\nAt Grōv, a Nu Skin company, ou...",3.9,Nu Skin\n3.9,"Vineyard, UT","Provo, UT",1001 to 5000 employees,1984,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),-1
43,Data Engineer,$81K-$131K (Glassdoor est.),POSITION SUMMARY\n\n\nThe candidate will be jo...,3.7,Bayview Asset Management\n3.7,"Coral Gables, FL","Coral Gables, FL",1001 to 5000 employees,1995,Company - Private,Investment Banking & Asset Management,Finance,$100 to $500 million (USD),-1
44,Patient Safety- Associate Data Scientist,$81K-$131K (Glassdoor est.),"Do you have expertise in, and passion for appl...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
45,Data Scientist,$81K-$131K (Glassdoor est.),Position Description:\n\nWant to make a differ...,3.4,Mathematica Policy Research\n3.4,"Washington, DC","Princeton, NJ",1001 to 5000 employees,1986,Company - Private,Consulting,Business Services,$100 to $500 million (USD),-1
46,Data Scientist,$81K-$131K (Glassdoor est.),Ready to write the best chapter of your career...,3.8,XSELL Technologies\n3.8,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
47,R&D Specialist/ Food Scientist,$81K-$131K (Glassdoor est.),Responsibilities Include but may not be limite...,2.6,Teasdale Latin Foods\n2.6,"Hoopeston, IL","Flower Mound, TX",501 to 1000 employees,-1,Company - Private,Food & Beverage Manufacturing,Manufacturing,$100 to $500 million (USD),-1
48,Analytics Consultant,$81K-$131K (Glassdoor est.),SpringML is seeking an Analytics Consultant to...,4.4,SpringML\n4.4,"Indianapolis, IN","Pleasanton, CA",1 to 50 employees,2015,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
49,Bioinformatics Scientist 1 – Algorithm and Dat...,$81K-$131K (Glassdoor est.),Our group is focused on tackling some of the m...,3.9,Illumina\n3.9,"San Diego, CA","San Diego, CA",5001 to 10000 employees,1998,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"Thermo Fisher Scientific, Roche"

In [6]:
df['hourly'] = df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)

In [7]:
df['employer_provided'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)

In [8]:
df = df[df['Salary Estimate'] !='-1']

In [9]:
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [10]:
remove_dlr_K = salary.apply(lambda x: x.replace('K','').replace('$',''))

In [11]:
hr_min = remove_dlr_K.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary:',''))

In [12]:
df['salary_min'] = hr_min.apply(lambda x: int(x.split('-')[0]))

In [13]:
df['salary_max'] = hr_min.apply(lambda x: int(x.split('-')[1]))

In [14]:
df['avg_salary'] = (df.salary_min+df.salary_max)/2

In [15]:
df['company_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating'] < 0 else x['Company Name'][:-3], axis = 1)

In [16]:
#df['job_state'] = df['Location'].apply(lambda x: x.split(',')[1])
#df.job_state.value_counts()

In [17]:
df['some_state'] = df.apply(lambda x: 1 if x.Location == x.Headquarters else 0, axis = 1)

In [18]:
df['age'] = df.Founded.apply(lambda x: x if x<1 else 2020 - x)

In [19]:
df['python_ym'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df.python_ym.value_counts()

1    28
0    22
Name: python_ym, dtype: int64

In [20]:
df['r_ym'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() else 0)
df.r_ym.value_counts()

0    50
Name: r_ym, dtype: int64

In [21]:
df['spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df.spark.value_counts()

0    43
1     7
Name: spark, dtype: int64

In [22]:
df['aws'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df.aws.value_counts()

0    39
1    11
Name: aws, dtype: int64

In [23]:
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df.excel.value_counts()

0    27
1    23
Name: excel, dtype: int64

In [24]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,salary_max,avg_salary,company_txt,some_state,age,python_ym,r_ym,spark,aws,excel
0,Data Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,...,106,85.0,Spring Health\n,1,4,1,0,0,0,1
1,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,...,106,85.0,ManTech\n,0,52,0,0,0,0,0
2,"Data Scientist - Statistics, Early Career",$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,106,85.0,Pacific Northwest National Laboratory\n,0,55,0,0,0,0,1
3,"Medical Laboratory Scientist (MLS), ASCP, MT",$64K-$106K (Glassdoor est.),Description of role: Collect and analyze toena...,3.7,Advanced Foot and Ankle Care\n3.7,"Memphis, TN","Nashville, TN",Unknown,-1,Company - Private,...,106,85.0,Advanced Foot and Ankle Care\n,0,-1,0,0,0,0,0
4,Data Scientist,$64K-$106K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,...,106,85.0,INFICON\n,0,20,1,0,0,1,1
5,Staff Data Scientist - Analytics,$64K-$106K (Glassdoor est.),Intuit is seeking a Staff Data Scientist to co...,4.4,Intuit - Data\n4.4,"San Diego, CA","Mountain View, CA",5001 to 10000 employees,1983,Company - Public,...,106,85.0,Intuit - Data\n,0,37,0,0,0,0,0
6,Sr Data Scientist,$64K-$106K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,...,106,85.0,Ecolab\n,0,97,1,0,0,1,0
7,Associate Business Intelligence Data Scientist,$64K-$106K (Glassdoor est.),"Blending customer advisory, customer support, ...",3.1,Carousel Industries\n3.1,"Exeter, RI","Exeter, RI",1001 to 5000 employees,1992,Company - Private,...,106,85.0,Carousel Industries\n,1,28,1,0,0,0,0
8,Data Scientist / Machine Learning Expert,$64K-$106K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,...,106,85.0,Novartis\n,0,24,1,0,0,0,0
9,Senior Data Scientist,$64K-$106K (Glassdoor est.),"At Recursion, nothing is more important than t...",4.7,Recursion Pharmaceuticals\n4.7,"Salt Lake City, UT","Salt Lake City, UT",51 to 200 employees,2013,Company - Private,...,106,85.0,Recursion Pharmaceuticals\n,1,7,1,0,0,1,1
10,Data Scientist,$64K-$106K (Glassdoor est.),Job Brief\n\nThe ideal candidate will have pre...,2.9,IFG Companies\n2.9,"New York, NY","Hartford, CT",201 to 500 employees,1985,Company - Private,...,106,85.0,IFG Companies\n,0,35,1,0,0,0,0
11,Data Analyst,$64K-$106K (Glassdoor est.),"Data Analyst\n\nLocation: Fort Meade, MD\n\nDe...",4.1,Favor TechConsulting\n4.1,"Fort Meade, MD","Vienna, VA",201 to 500 employees,2007,Company - Private,...,106,85.0,Favor TechConsulting\n,0,13,0,0,0,0,1
12,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),Business Intelligence Analyst\nFull Time\nRemo...,3.2,Radius Global Solutions\n3.2,"Ambler, PA","Ambler, PA",1001 to 5000 employees,2013,Company - Private,...,106,85.0,Radius Global Solutions\n,1,7,1,0,0,0,1
13,VP Data Science & Analytics,$64K-$106K (Glassdoor est.),It's fun to work in a company where people tru...,3.6,Green Dot\n3.6,California,"Pasadena, CA",1001 to 5000 employees,1999,Company - Public,...,106,85.0,Green Dot\n,0,21,0,0,0,0,0
14,Senior Data Scientist,$64K-$106K (Glassdoor est.),"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck\n3.8,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,...,106,85.0,GutCheck\n,1,11,0,0,0,0,0
15,Data Scientist in Artificial Intelligence - In...,$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310507\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,106,85.0,PNNL\n,1,55,0,0,0,0,0
16,Sensory Scientist,$64K-$106K (Glassdoor est.),A leading food production company in St. Louis...,3.8,NIC Infotek\n3.8,"Saint Louis, MO","Tampa, FL",51 to 200 employees,2004,Company - Public,...,106,85.0,NIC Infotek\n,0,16,0,0,0,0,1
17,Medical Lab Scientist,$64K-$106K (Glassdoor est.),"Overview\n\n\nTower Health is a strong, region...",3.5,Tower Health\n3.5,"West Grove, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,...,106,85.0,Tower Health\n,0,3,0,0,0,0,0
18,Data Scientist,$64K-$106K (Glassdoor est.),Northrop Grumman Space Systems is looking for ...,3.7,Northrop Grumman\n3.7,"McLean, VA","Falls Church, VA",10000+ employees,1939,Company - Public,...,106,85.0,Northrop Grumman\n,0,81,1,0,0,0,0
19,Data Scientist-Human Resources,$64K-$106K (Glassdoor est.),"Lexington, MA, US\n\n#job-location.job-locatio...",3.8,MIT Lincoln Laboratory\n3.8,"Lexington, MA","Lexington, MA",1001 to 5000 employees,1951,Nonprofit Organization,...,106,85.0,MIT Lincoln Laboratory\n,1,69,1,0,1,0,0
20,Senior Healthcare Data Analyst - Contract Mode...,$64K-$106K (Glassdoor est.),"About Fallon Health\nFounded in 1977, Fallon H...",2.8,Fallon Health\n2.8,"Worcester, MA","Worcester, MA",1001 to 5000 employees,1977,Nonprofit Organization,...,106,85.0,Fallon Health\n,1,43,0,0,0,1,1
21,Senior Data Scientist,$64K-$106K (Glassdoor est.),Summary\n\nWe’re looking for a senior data sci...,3.6,TRANZACT\n3.6,United States,"Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,...,106,85.0,TRANZACT\n,0,31,1,0,0,0,1
22,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),"Who Are We?\n\nMerchantE is an innovative, tec...",3.0,MerchantE\n3.0,"Alpharetta, GA","Alpharetta, GA",201 to 500 employees,2000,Subsidiary or Business Segment,...,106,85.0,MerchantE\n,1,20,0,0,0,0,1
23,Data Scientist,$64K-$106K (Glassdoor est.),The Senior Data Scientist will build and impro...,3.6,Powertek\n3.6,"Washington, DC","Rockville, MD",51 to 200 employees,2001,Company - Private,...,106,85.0,Powertek\n,0,19,0,0,0,0,0
24,Data Scientist,$64K-$106K (Glassdoor est.),The Data Scientist supports the development of...,3.4,Plymouth Rock Assurance\n3.4,"Woodbridge, NJ","Boston, MA",1001 to 5000 employees,1982,Company - Private,...,106,85.0,Plymouth Rock Assurance\n,0,38,0,0,0,0,1
25,Sr Data Scientist,$64K-$106K (Glassdoor est.),"About Figure\n\nAt Figure, we're on a mission ...",4.5,Figure\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2018,Company - Private,...,106,85.0,Figure\n,1,2,1,0,1,1,1
26,"Data Analyst, Ethics & Compliance",$64K-$106K (Glassdoor est.),Job Description\n\n\nTitle: Data Analyst\n\n\n...,4.2,Cogent Infotech\n4.2,"Stamford, CT","Pittsburgh, PA",201 to 500 employees,2003,Company - Private,...,106,85.0,Cogent Infotech\n,0,17,0,0,0,0,1
27,Research Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,...,106,85.0,Spring Health\n,1,4,1,0,0,0,1
28,Data Scientist,$64K-$106K (Glassdoor est.),The world's largest and fastest-growing compan...,4.5,Demandbase\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2006,Company - Private,...,106,85.0,Demandbase\n,1,14,1,0,1,1,0
29,"Real World Science, Data Scientist",$64K-$106K (Glassdoor est.),"Title: Real World Science, Data Scientist\nLoc...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,...,106,85.0,AstraZeneca\n,0,107,1,0,0,0,0
30,Sr Data Scientist,$81K-$131K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,...,131,106.0,Ecolab\n,0,97,1,0,0,1,0
31,"Data Scientist - Statistics, Early Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,131,106.0,Pacific Northwest National Laboratory\n,0,55,0,0,0,0,1
32,Data Scientist,$81K-$131K (Glassdoor est.),Back to search results\nPrevious job\n\nNext j...,3.9,Mars\n3.9,United States,"Mc Lean, VA",10000+ employees,1911,Company - Private,...,131,106.0,Mars\n,0,109,1,0,1,1,0
33,"Senior Manager, Clients Analytics (Data Science)",$81K-$131K (Glassdoor est.),The Opportunity\n\n\nCome build the data and a...,4.5,Livongo\n4.5,"Denver, CO","Mountain View, CA",501 to 1000 employees,2014,Company - Public,...,131,106.0,Livongo\n,0,6,1,0,0,0,0
34,Data Scientist #5967,$81K-$131K (Glassdoor est.),Company Overview\n\nFanatics is the global lea...,3.4,Fanatics\n3.4,"San Mateo, CA","Jacksonville, FL",5001 to 10000 employees,1996,Company - Private,...,131,106.0,Fanatics\n,0,24,0,0,1,0,0
35,Senior Analyst/Data Scientist,$81K-$131K (Glassdoor est.),At Edmunds were driven to make car buying easi...,3.5,Edmunds.com\n3.5,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,1966,Company - Private,...,131,106.0,Edmunds.com\n,1,54,1,0,0,1,1
36,Data Scientist,$81K-$131K (Glassdoor est.),Job Title: Data Scientists\n\nJob Description\...,2.2,Great-Circle Technologies\n2.2,"Chantilly, VA","Chantilly, VA",1 to 50 employees,2000,Company - Private,...,131,106.0,Great-Circle Technologies\n,1,20,1,0,1,1,1
37,Business Intelligence Analyst,$81K-$131K (Glassdoor est.),"Reporting to the Director, Marketing Analytics...",3.7,Zimmerman Advertising\n3.7,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 to 1000 employees,1984,Subsidiary or Business Segment,...,131,106.0,Zimmerman Advertising\n,1,36,0,0,0,0,1
38,Data Scientist,$81K-$131K (Glassdoor est.),It's fun to work in a company where people tru...,3.3,NAVEX Global\n3.3,"Lake Oswego, OR","Lake Oswego, OR",1001 to 5000 employees,2012,Company - Private,...,131,106.0,NAVEX Global\n,1,8,1,0,1,0,0
39,Data Analyst,$81K-$131K (Glassdoor est.),File #: 2020-26-0616\nPosition: Data Analyst –...,4.4,Shared Services West\n4.4,Remote,"Burlington, Canada",51 to 200 employees,2001,Nonprofit Organization,...,131,106.0,Shared Services West\n,0,19,0,0,0,0,1
40,"Data Scientist - Statistics, Mid-Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310919\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,131,106.0,Pacific Northwest National Laboratory\n,1,55,0,0,0,0,0
41,"Risk and Analytics IT, Data Scientist",$81K-$131K (Glassdoor est.),OUR AGENCY\n\nMaking a Difference\n\nSWIB is a...,2.9,State of Wisconsin Investment Board\n2.9,"Madison, WI","Madison, WI",51 to 200 employees,1951,Government,...,131,106.0,State of Wisconsin Investment Board\n,1,69,1,0,0,0,0
42,Research Scientist,$81K-$131K (Glassdoor est.),"Job Summary:\n\nAt Grōv, a Nu Skin company, ou...",3.9,Nu Skin\n3.9,"Vineyard, UT","Provo, UT",1001 to 5000 employees,1984,Company - Public,...,131,106.0,Nu Skin\n,0,36,0,0,0,0,1
43,Data Engineer,$81K-$131K (Glassdoor est.),POSITION SUMMARY\n\n\nThe candidate will be jo...,3.7,Bayview Asset Management\n3.7,"Coral Gables, FL","Coral Gables, FL",1001 to 5000 employees,1995,Company - Private,...,131,106.0,Bayview Asset Management\n,1,25,1,0,0,0,0
44,Patient Safety- Associate Data Scientist,$81K-$131K (Glassdoor est.),"Do you have expertise in, and passion for appl...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,...,131,106.0,AstraZeneca\n,0,107,1,0,0,0,1
45,Data Scientist,$81K-$131K (Glassdoor est.),Position Description:\n\nWant to make a differ...,3.4,Mathematica Policy Research\n3.4,"Washington, DC","Princeton, NJ",1001 to 5000 employees,1986,Company - Private,...,131,106.0,Mathematica Policy Research\n,0,34,1,0,0,1,1
46,Data Scientist,$81K-$131K (Glassdoor est.),Ready to write the best chapter of your career...,3.8,XSELL Technologies\n3.8,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,...,131,106.0,XSELL Technologies\n,1,6,1,0,0,0,0
47,R&D Specialist/ Food Scientist,$81K-$131K (Glassdoor est.),Responsibilities Include but may not be limite...,2.6,Teasdale Latin Foods\n2.6,"Hoopeston, IL","Flower Mound, TX",501 to 1000 employees,-1,Company - Private,...,131,106.0,Teasdale Latin Foods\n,0,-1,0,0,0,0,0
48,Analytics Consultant,$81K-$131K (Glassdoor est.),SpringML is seeking an Analytics Consultant to...,4.4,SpringML\n4.4,"Indianapolis, IN","Pleasanton, CA",1 to 50 employees,2015,Company - Private,...,131,106.0,SpringML\n,0,5,1,0,0,0,0
49,Bioinformatics Scientist 1 – Algorithm and Dat...,$81K-$131K (Glassdoor est.),Our group is focused on tackling some of the m...,3.9,Illumina\n3.9,"San Diego, CA","San Diego, CA",5001 to 10000 employees,1998,Company - Public,...,131,106.0,Illumina\n,1,22,1,0,0,0,1

In [25]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'salary_min', 'salary_max', 'avg_salary',
       'company_txt', 'some_state', 'age', 'python_ym', 'r_ym', 'spark', 'aws',
       'excel'],
      dtype='object')

In [26]:
df.to_csv('C:/Users/Owner/Documents/salary_project/salary_proj/data_cleaning.csv', index = False)

In [27]:
pd.read_csv('C:/Users/Owner/Documents/salary_project/salary_proj/data_cleaning.csv')

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,salary_max,avg_salary,company_txt,some_state,age,python_ym,r_ym,spark,aws,excel
0,Data Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,...,106,85.0,Spring Health\n,1,4,1,0,0,0,1
1,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,...,106,85.0,ManTech\n,0,52,0,0,0,0,0
2,"Data Scientist - Statistics, Early Career",$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,106,85.0,Pacific Northwest National Laboratory\n,0,55,0,0,0,0,1
3,"Medical Laboratory Scientist (MLS), ASCP, MT",$64K-$106K (Glassdoor est.),Description of role: Collect and analyze toena...,3.7,Advanced Foot and Ankle Care\n3.7,"Memphis, TN","Nashville, TN",Unknown,-1,Company - Private,...,106,85.0,Advanced Foot and Ankle Care\n,0,-1,0,0,0,0,0
4,Data Scientist,$64K-$106K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,...,106,85.0,INFICON\n,0,20,1,0,0,1,1
5,Staff Data Scientist - Analytics,$64K-$106K (Glassdoor est.),Intuit is seeking a Staff Data Scientist to co...,4.4,Intuit - Data\n4.4,"San Diego, CA","Mountain View, CA",5001 to 10000 employees,1983,Company - Public,...,106,85.0,Intuit - Data\n,0,37,0,0,0,0,0
6,Sr Data Scientist,$64K-$106K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,...,106,85.0,Ecolab\n,0,97,1,0,0,1,0
7,Associate Business Intelligence Data Scientist,$64K-$106K (Glassdoor est.),"Blending customer advisory, customer support, ...",3.1,Carousel Industries\n3.1,"Exeter, RI","Exeter, RI",1001 to 5000 employees,1992,Company - Private,...,106,85.0,Carousel Industries\n,1,28,1,0,0,0,0
8,Data Scientist / Machine Learning Expert,$64K-$106K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,...,106,85.0,Novartis\n,0,24,1,0,0,0,0
9,Senior Data Scientist,$64K-$106K (Glassdoor est.),"At Recursion, nothing is more important than t...",4.7,Recursion Pharmaceuticals\n4.7,"Salt Lake City, UT","Salt Lake City, UT",51 to 200 employees,2013,Company - Private,...,106,85.0,Recursion Pharmaceuticals\n,1,7,1,0,0,1,1
10,Data Scientist,$64K-$106K (Glassdoor est.),Job Brief\n\nThe ideal candidate will have pre...,2.9,IFG Companies\n2.9,"New York, NY","Hartford, CT",201 to 500 employees,1985,Company - Private,...,106,85.0,IFG Companies\n,0,35,1,0,0,0,0
11,Data Analyst,$64K-$106K (Glassdoor est.),"Data Analyst\n\nLocation: Fort Meade, MD\n\nDe...",4.1,Favor TechConsulting\n4.1,"Fort Meade, MD","Vienna, VA",201 to 500 employees,2007,Company - Private,...,106,85.0,Favor TechConsulting\n,0,13,0,0,0,0,1
12,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),Business Intelligence Analyst\nFull Time\nRemo...,3.2,Radius Global Solutions\n3.2,"Ambler, PA","Ambler, PA",1001 to 5000 employees,2013,Company - Private,...,106,85.0,Radius Global Solutions\n,1,7,1,0,0,0,1
13,VP Data Science & Analytics,$64K-$106K (Glassdoor est.),It's fun to work in a company where people tru...,3.6,Green Dot\n3.6,California,"Pasadena, CA",1001 to 5000 employees,1999,Company - Public,...,106,85.0,Green Dot\n,0,21,0,0,0,0,0
14,Senior Data Scientist,$64K-$106K (Glassdoor est.),"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck\n3.8,"Denver, CO","Denver, CO",51 to 200 employees,2009,Company - Private,...,106,85.0,GutCheck\n,1,11,0,0,0,0,0
15,Data Scientist in Artificial Intelligence - In...,$64K-$106K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310507\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,106,85.0,PNNL\n,1,55,0,0,0,0,0
16,Sensory Scientist,$64K-$106K (Glassdoor est.),A leading food production company in St. Louis...,3.8,NIC Infotek\n3.8,"Saint Louis, MO","Tampa, FL",51 to 200 employees,2004,Company - Public,...,106,85.0,NIC Infotek\n,0,16,0,0,0,0,1
17,Medical Lab Scientist,$64K-$106K (Glassdoor est.),"Overview\n\n\nTower Health is a strong, region...",3.5,Tower Health\n3.5,"West Grove, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,...,106,85.0,Tower Health\n,0,3,0,0,0,0,0
18,Data Scientist,$64K-$106K (Glassdoor est.),Northrop Grumman Space Systems is looking for ...,3.7,Northrop Grumman\n3.7,"McLean, VA","Falls Church, VA",10000+ employees,1939,Company - Public,...,106,85.0,Northrop Grumman\n,0,81,1,0,0,0,0
19,Data Scientist-Human Resources,$64K-$106K (Glassdoor est.),"Lexington, MA, US\n\n#job-location.job-locatio...",3.8,MIT Lincoln Laboratory\n3.8,"Lexington, MA","Lexington, MA",1001 to 5000 employees,1951,Nonprofit Organization,...,106,85.0,MIT Lincoln Laboratory\n,1,69,1,0,1,0,0
20,Senior Healthcare Data Analyst - Contract Mode...,$64K-$106K (Glassdoor est.),"About Fallon Health\nFounded in 1977, Fallon H...",2.8,Fallon Health\n2.8,"Worcester, MA","Worcester, MA",1001 to 5000 employees,1977,Nonprofit Organization,...,106,85.0,Fallon Health\n,1,43,0,0,0,1,1
21,Senior Data Scientist,$64K-$106K (Glassdoor est.),Summary\n\nWe’re looking for a senior data sci...,3.6,TRANZACT\n3.6,United States,"Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,...,106,85.0,TRANZACT\n,0,31,1,0,0,0,1
22,Business Intelligence Analyst,$64K-$106K (Glassdoor est.),"Who Are We?\n\nMerchantE is an innovative, tec...",3.0,MerchantE\n3.0,"Alpharetta, GA","Alpharetta, GA",201 to 500 employees,2000,Subsidiary or Business Segment,...,106,85.0,MerchantE\n,1,20,0,0,0,0,1
23,Data Scientist,$64K-$106K (Glassdoor est.),The Senior Data Scientist will build and impro...,3.6,Powertek\n3.6,"Washington, DC","Rockville, MD",51 to 200 employees,2001,Company - Private,...,106,85.0,Powertek\n,0,19,0,0,0,0,0
24,Data Scientist,$64K-$106K (Glassdoor est.),The Data Scientist supports the development of...,3.4,Plymouth Rock Assurance\n3.4,"Woodbridge, NJ","Boston, MA",1001 to 5000 employees,1982,Company - Private,...,106,85.0,Plymouth Rock Assurance\n,0,38,0,0,0,0,1
25,Sr Data Scientist,$64K-$106K (Glassdoor est.),"About Figure\n\nAt Figure, we're on a mission ...",4.5,Figure\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2018,Company - Private,...,106,85.0,Figure\n,1,2,1,0,1,1,1
26,"Data Analyst, Ethics & Compliance",$64K-$106K (Glassdoor est.),Job Description\n\n\nTitle: Data Analyst\n\n\n...,4.2,Cogent Infotech\n4.2,"Stamford, CT","Pittsburgh, PA",201 to 500 employees,2003,Company - Private,...,106,85.0,Cogent Infotech\n,0,17,0,0,0,0,1
27,Research Scientist,$64K-$106K (Glassdoor est.),***Please note: All hiring and recruitment at ...,3.6,Spring Health\n3.6,"New York, NY","New York, NY",1 to 50 employees,2016,Company - Private,...,106,85.0,Spring Health\n,1,4,1,0,0,0,1
28,Data Scientist,$64K-$106K (Glassdoor est.),The world's largest and fastest-growing compan...,4.5,Demandbase\n4.5,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2006,Company - Private,...,106,85.0,Demandbase\n,1,14,1,0,1,1,0
29,"Real World Science, Data Scientist",$64K-$106K (Glassdoor est.),"Title: Real World Science, Data Scientist\nLoc...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,...,106,85.0,AstraZeneca\n,0,107,1,0,0,0,0
30,Sr Data Scientist,$81K-$131K (Glassdoor est.),"JOB DUTIES:Senior Data Scientist for Ecolab, I...",3.6,Ecolab\n3.6,"Naperville, IL","Saint Paul, MN",10000+ employees,1923,Company - Public,...,131,106.0,Ecolab\n,0,97,1,0,0,1,0
31,"Data Scientist - Statistics, Early Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310918\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Seattle, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,131,106.0,Pacific Northwest National Laboratory\n,0,55,0,0,0,0,1
32,Data Scientist,$81K-$131K (Glassdoor est.),Back to search results\nPrevious job\n\nNext j...,3.9,Mars\n3.9,United States,"Mc Lean, VA",10000+ employees,1911,Company - Private,...,131,106.0,Mars\n,0,109,1,0,1,1,0
33,"Senior Manager, Clients Analytics (Data Science)",$81K-$131K (Glassdoor est.),The Opportunity\n\n\nCome build the data and a...,4.5,Livongo\n4.5,"Denver, CO","Mountain View, CA",501 to 1000 employees,2014,Company - Public,...,131,106.0,Livongo\n,0,6,1,0,0,0,0
34,Data Scientist #5967,$81K-$131K (Glassdoor est.),Company Overview\n\nFanatics is the global lea...,3.4,Fanatics\n3.4,"San Mateo, CA","Jacksonville, FL",5001 to 10000 employees,1996,Company - Private,...,131,106.0,Fanatics\n,0,24,0,0,1,0,0
35,Senior Analyst/Data Scientist,$81K-$131K (Glassdoor est.),At Edmunds were driven to make car buying easi...,3.5,Edmunds.com\n3.5,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,1966,Company - Private,...,131,106.0,Edmunds.com\n,1,54,1,0,0,1,1
36,Data Scientist,$81K-$131K (Glassdoor est.),Job Title: Data Scientists\n\nJob Description\...,2.2,Great-Circle Technologies\n2.2,"Chantilly, VA","Chantilly, VA",1 to 50 employees,2000,Company - Private,...,131,106.0,Great-Circle Technologies\n,1,20,1,0,1,1,1
37,Business Intelligence Analyst,$81K-$131K (Glassdoor est.),"Reporting to the Director, Marketing Analytics...",3.7,Zimmerman Advertising\n3.7,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 to 1000 employees,1984,Subsidiary or Business Segment,...,131,106.0,Zimmerman Advertising\n,1,36,0,0,0,0,1
38,Data Scientist,$81K-$131K (Glassdoor est.),It's fun to work in a company where people tru...,3.3,NAVEX Global\n3.3,"Lake Oswego, OR","Lake Oswego, OR",1001 to 5000 employees,2012,Company - Private,...,131,106.0,NAVEX Global\n,1,8,1,0,1,0,0
39,Data Analyst,$81K-$131K (Glassdoor est.),File #: 2020-26-0616\nPosition: Data Analyst –...,4.4,Shared Services West\n4.4,Remote,"Burlington, Canada",51 to 200 employees,2001,Nonprofit Organization,...,131,106.0,Shared Services West\n,0,19,0,0,0,0,1
40,"Data Scientist - Statistics, Mid-Career",$81K-$131K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310919\n\n...,3.8,Pacific Northwest National Laboratory\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,131,106.0,Pacific Northwest National Laboratory\n,1,55,0,0,0,0,0
41,"Risk and Analytics IT, Data Scientist",$81K-$131K (Glassdoor est.),OUR AGENCY\n\nMaking a Difference\n\nSWIB is a...,2.9,State of Wisconsin Investment Board\n2.9,"Madison, WI","Madison, WI",51 to 200 employees,1951,Government,...,131,106.0,State of Wisconsin Investment Board\n,1,69,1,0,0,0,0
42,Research Scientist,$81K-$131K (Glassdoor est.),"Job Summary:\n\nAt Grōv, a Nu Skin company, ou...",3.9,Nu Skin\n3.9,"Vineyard, UT","Provo, UT",1001 to 5000 employees,1984,Company - Public,...,131,106.0,Nu Skin\n,0,36,0,0,0,0,1
43,Data Engineer,$81K-$131K (Glassdoor est.),POSITION SUMMARY\n\n\nThe candidate will be jo...,3.7,Bayview Asset Management\n3.7,"Coral Gables, FL","Coral Gables, FL",1001 to 5000 employees,1995,Company - Private,...,131,106.0,Bayview Asset Management\n,1,25,1,0,0,0,0
44,Patient Safety- Associate Data Scientist,$81K-$131K (Glassdoor est.),"Do you have expertise in, and passion for appl...",3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,...,131,106.0,AstraZeneca\n,0,107,1,0,0,0,1
45,Data Scientist,$81K-$131K (Glassdoor est.),Position Description:\n\nWant to make a differ...,3.4,Mathematica Policy Research\n3.4,"Washington, DC","Princeton, NJ",1001 to 5000 employees,1986,Company - Private,...,131,106.0,Mathematica Policy Research\n,0,34,1,0,0,1,1
46,Data Scientist,$81K-$131K (Glassdoor est.),Ready to write the best chapter of your career...,3.8,XSELL Technologies\n3.8,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,...,131,106.0,XSELL Technologies\n,1,6,1,0,0,0,0
47,R&D Specialist/ Food Scientist,$81K-$131K (Glassdoor est.),Responsibilities Include but may not be limite...,2.6,Teasdale Latin Foods\n2.6,"Hoopeston, IL","Flower Mound, TX",501 to 1000 employees,-1,Company - Private,...,131,106.0,Teasdale Latin Foods\n,0,-1,0,0,0,0,0
48,Analytics Consultant,$81K-$131K (Glassdoor est.),SpringML is seeking an Analytics Consultant to...,4.4,SpringML\n4.4,"Indianapolis, IN","Pleasanton, CA",1 to 50 employees,2015,Company - Private,...,131,106.0,SpringML\n,0,5,1,0,0,0,0
49,Bioinformatics Scientist 1 – Algorithm and Dat...,$81K-$131K (Glassdoor est.),Our group is focused on tackling some of the m...,3.9,Illumina\n3.9,"San Diego, CA","San Diego, CA",5001 to 10000 employees,1998,Company - Public,...,131,106.0,Illumina\n,1,22,1,0,0,0,1